name: build wheels

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build multiarch Python3 wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build wheels
        run: pip wheel --no-deps -w /tmp/wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: pypi_test_ameynert-wheel
          path: /tmp/wheelhouse/pypi_test_ameynert*.whl
          if-no-files-found: error
